# Generated by Django 5.2.11 on 2026-04-09 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('inward_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('plant', models.CharField(blank=True, max_length=100, null=True)),
                ('location_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('inward_date', models.DateField(auto_now_add=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producttransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('transfer_type', models.CharField(blank=True, choices=[('WAREHOUSE_TO_WAREHOUSE', 'Warehouse To Warehouse'), ('STORE_TO_WAREHOUSE', 'Store To Warehouse'), ('WAREHOUSE_TO_STORE', 'Warehouse To Store'), ('STORE_TO_STORE', 'Store To Store'), ('LOCATION_TO_LOCATION', 'Location To Location'), ('PLANT_TO_LOCATION', 'Plant To Location'), ('LOCATION_TO_PLANT', 'Location To Plant'), ('PLANT_TO_PLANT', 'Plant To Plant')], max_length=50, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=255, null=True)),
                ('from_store', models.CharField(blank=True, max_length=255, null=True)),
                ('to_store', models.CharField(blank=True, max_length=255, null=True)),
                ('from_subinventory', models.CharField(blank=True, max_length=255, null=True)),
                ('to_subinventory', models.CharField(blank=True, max_length=255, null=True)),
                ('from_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('to_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InwardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('sub_inventory', models.CharField(max_length=100)),
                ('inventory_type', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('sub_zone', models.CharField(max_length=100)),
                ('inward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.inward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='warehouse.producttransfer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
