# Generated by Django 5.2.11 on 2026-04-16 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PutawayHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('putaway_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('grv_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_inventory', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('SUBINVENTORY_TO_SUBINVENTORY', 'Subinventory To Subinventory'), ('STORE_TO_SUBINVENTORY', 'Store To Subinventory'), ('LOCATION_TO_LOCATION', 'Location To Location'), ('PLANT_TO_LOCATION', 'Plant To Location'), ('LOCATION_TO_PLANT', 'Location To Plant'), ('PLANT_TO_PLANT', 'Plant To Plant'), ('ZONE', 'Zone'), ('SUBINVENTORY_TO_ZONE', 'Subinventory To Zone'), ('ZONE_TO_SUBINVENTORY', 'Zone To Subinventory')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PutawayLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('grv_line_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_code', models.CharField(blank=True, max_length=100, null=True)),
                ('aisle_code', models.CharField(blank=True, max_length=100, null=True)),
                ('rack_code', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_code', models.CharField(blank=True, max_length=100, null=True)),
                ('allocated_qty', models.FloatField()),
                ('putaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.putawayheader')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
