# Generated by Django 5.2.11 on 2026-04-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_putawayheader_alter_producttransfer_transfer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putawayline',
            name='putaway',
        ),
        migrations.AddField(
            model_name='putawayline',
            name='sub_inventory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='putawayline',
            name='aisle_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='putawayline',
            name='bin_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='putawayline',
            name='grv_line_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='putawayline',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='putawayline',
            name='rack_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='putawayline',
            name='zone_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PutawayHeader',
        ),
    ]
