# Generated by Django 5.2.11 on 2026-04-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_putawayline_putaway_putawayline_sub_inventory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PutawayLine',
            new_name='Allocation',
        ),
        migrations.AlterModelTable(
            name='allocation',
            table='putaway_allocation',
        ),
    ]
