# Generated by Django 5.2.11 on 2026-04-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_rename_putawayline_allocation_alter_allocation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='inwarditem',
            name='sub_zone',
        ),
        migrations.RemoveField(
            model_name='inwarditem',
            name='zone',
        ),
    ]
