# Generated by Django 5.2.11 on 2026-04-20 07:13

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_remove_inward_location_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttransfer',
            old_name='from_store',
            new_name='from_bin',
        ),
        migrations.RenameField(
            model_name='producttransfer',
            old_name='plant_code',
            new_name='from_plant',
        ),
        migrations.RenameField(
            model_name='producttransfer',
            old_name='to_store',
            new_name='from_rack',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='available_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='to_bin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='to_plant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='to_rack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='transfer_date',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='producttransfer',
            name='transfer_mode',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='product_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='transfer_type',
            field=models.CharField(choices=[('PLANT_TO_PLANT', 'Plant to Plant'), ('SUBINVENTORY_TO_SUBINVENTORY', 'Subinventory to Subinventory'), ('ZONE_TO_ZONE', 'Zone to Zone'), ('RACK_TO_RACK', 'Rack to Rack'), ('BIN_TO_BIN', 'Bin to Bin')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
