# Generated by Django 5.2.11 on 2026-04-20 12:04

import django_api_mixins.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_rename_from_store_producttransfer_from_bin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('requisition_num', models.CharField(blank=True, max_length=100, null=True)),
                ('workstation', models.CharField()),
                ('sub_inventory', models.CharField()),
                ('product', models.CharField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'requisition',
            },
            bases=(models.Model, django_api_mixins.mixins.ModelMixin),
        ),
    ]
