# Generated by Django 5.2.11 on 2026-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_requisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
