# Generated by Django 5.2.11 on 2026-04-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_requisition_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttransfer',
            old_name='from_bin',
            new_name='from_location',
        ),
        migrations.RenameField(
            model_name='producttransfer',
            old_name='to_bin',
            new_name='to_location',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='available_qty',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='from_plant',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='from_rack',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='from_subinventory',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='from_zone',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='to_plant',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='to_rack',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='to_subinventory',
        ),
        migrations.RemoveField(
            model_name='producttransfer',
            name='to_zone',
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Completed', 'Completed'), ('In Transit', 'In Transit')], default='Pending Approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='transfer_mode',
            field=models.CharField(blank=True, choices=[('Internal Transfer', 'Internal Transfer'), ('External Transfer', 'External Transfer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('SubInventory to SubInventory', 'Subinventory To Subinventory'), ('Plant to Plant', 'Plant To Plant'), ('Zone to Zone', 'Zone To Zone'), ('Aisle to Aisle', 'Aisle To Aisle')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Close', 'Close')], default='Open', max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='producttransfer',
            table='Product_transfer',
        ),
    ]
