# Generated by Django 5.2.11 on 2026-04-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_rename_from_bin_producttransfer_from_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='unallocated_qty',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
