# Generated by Django 5.2.11 on 2026-04-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_allocation_unallocated_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='grv_line_id',
            new_name='grn_number',
        ),
    ]
