# Generated by Django 5.2.11 on 2026-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_rename_grv_line_id_allocation_grn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocated_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='unallocated_qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
