# Generated by Django 5.2.11 on 2026-04-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_alter_allocation_allocated_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('SubInventory to SubInventory', 'Subinventory To Subinventory'), ('Plant to Plant', 'Plant To Plant'), ('Zone to Zone', 'Zone To Zone'), ('Aisle to Aisle', 'Aisle To Aisle'), ('Bin to Bin', 'Bin To Bin')], max_length=50, null=True),
        ),
    ]
