# Generated by Django 5.2.11 on 2026-04-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_alter_producttransfer_transfer_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='producttransfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('SubInventory to SubInventory', 'Subinventory To Subinventory'), ('Plant to Plant', 'Plant To Plant'), ('Zone to Zone', 'Zone To Zone'), ('Aisle to Aisle', 'Aisle To Aisle'), ('Bin to Bin', 'Bin To Bin'), ('Rack to Rack', 'Rack To Rack')], max_length=50, null=True),
        ),
    ]
