# Generated by Django 5.2.11 on 2026-04-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_alter_allocation_options_alter_requisition_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='sub_inventory',
            new_name='to_sub_inventory',
        ),
        migrations.AddField(
            model_name='requisition',
            name='from_sub_inventory',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('accept', 'accept'), ('reject', 'reject'), ('close', 'close')], default='open', max_length=100, null=True),
        ),
    ]
