# Generated by Django 5.2.11 on 2026-05-02 16:55

import django.db.models.deletion
import django_api_mixins.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_alter_requisition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('accepted', 'accepted'), ('partial accepted', 'partial accepted'), ('rejected', 'rejected'), ('closed', 'closed')], default='open', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RequisitionIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_issues', to='warehouse.requisition')),
            ],
            options={
                'db_table': 'requisition_issue',
                'ordering': ('-id',),
            },
            bases=(models.Model, django_api_mixins.mixins.ModelMixin),
        ),
    ]
